{{- $cn := "nauta-experiment-service.nauta.svc" -}}
{{- $ca := genCA $cn 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca -}}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    api: {{ .Release.Name }}-{{ .Chart.Name }}
    apiserver: "true"
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.aggregator.aipg.intel.com
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
    api: {{ .Chart.Name }}
    apiserver: "true"
spec:
  version: v1
  group: aggregator.aipg.intel.com
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}
  versionPriority: 10
  caBundle: {{ b64enc $cert.Cert }}
  insecureSkipTLSVerify: false
