apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - aggregator.aipg.intel.com
    resources:
      - runs
    verbs:
      - "*"
  - nonResourceURLs:
      - "/"
    verbs:
      - get
  - apiGroups:
      - "*"
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
