---
apiVersion: "aggregator.aipg.intel.com/v1"
kind: Run
metadata:
  name: test-1
  labels:
    intel: "yes"
spec:
  pod-count: 1
  experiment-name: exp-test
  pod-selector:
    matchLabels:
      app: test-app
  parameters:
    - param1
    - param2
  metrics:
    accuracy: "52"
    test: "xxx"
  state: "RUNNING"
