# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

JupyterPort: 8888

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

service:
  type: ClusterIP

resources:
  requests:
    cpu: 38
    memory: 120Gi
  limits:
    cpu: 38
    memory: 120Gi

cpu: null
memory: null

experimentName:  {{ NAUTA.ExperimentName }} 
podCount: 1
