---

local_images:
  bin/kubectl:
    version: "1.10.11"
    required:
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../bin-containers/kubectl"
    artifacts:
      - src: /out/*
        dest: Linux/amd64
    push: False
  bin/loader:
    version: "1.0.0"
    required:
      BUILD_IMAGE: "shared/centos/build-go"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../applications/loader"
    artifacts:
      - src: /loader
        dest: Linux/amd64
    push: False
  bin/helm:
    version: "2.11.0"
    required:
      HELM_DATA_IMAGE: "shared/build/helm"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../bin-containers/helm"
    artifacts:
      - src: /out/*
        dest: Linux/amd64
    push: False
  bin/pip:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../bin-containers/pip"
    artifacts:
      - src: /out/*
        dest: pip
    push: False
  bin/centos/ansible:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos/python36"
      PIP_IMAGE: "bin/pip"
    method: build
    directory: "{{ playbook_dir }}/../../bin-containers/binary/centos"
    artifacts:
      - src: /out/*
        dest: Linux/amd64/CENTOS/7
      - src: /out/*
        dest: Linux/amd64/REDHAT/7.5
    push: False
