---

proxy:
  http_proxy: "{{ lookup('env','http_proxy') }}"
  HTTP_PROXY: "{{ lookup('env','http_proxy') }}"
  https_proxy: "{{ lookup('env','https_proxy') }}"
  HTTPS_PROXY: "{{ lookup('env','https_proxy') }}"
  no_proxy: "{{ lookup('env','no_proxy') }}"
  NO_PROXY: "{{ lookup('env','no_proxy') }}"

images: "{{ shared_images | combine(local_images | default({})) }}"

shared_images:
  shared/ubuntu:
    version: "16.04"
    method: "pull"
    push: False
    image: "ubuntu:16.04"
  shared/nonredist/ubuntu1804:
    version: "18.04"
    method: "pull"
    push: False
    image: "ubuntu:bionic-20180821"
  shared/centos:
    version: "7.6.1810"
    method: "build"
    push: False
    directory: "{{ playbook_dir }}/../../shared-containers/centos/core"
    required: {}
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/centos/centos-docker-1553589255.tar.xz
        dest: centos-docker.tar.xz
        checksum: 9f5c3bb6644f8a7e2a1c788668bbd7a29ef4c44bcffe3a7f1ed2cade9b123196
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/centos/icu4c-63_1-src.tgz
        dest: icu4c-63_1-src.tgz
        checksum: 05c490b69454fce5860b7e8e2821231674af0a11d7ef2febea9a32512998cb9d
  shared/centos/rpm-packer:
    version: "7.6.1810"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/rpm-packer"
    push: False
    args:
      USER_UID: "{{ user_id }}"
  shared/docs:
    version: "v0.0.1"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../docs"
    dockerfile: "{{ playbook_dir }}/../../shared-containers/docs/Dockerfile"
    push: False
    args:
      DOCS_VERSION: "{{ VERSION_MAJOR }}.{{ VERSION_MINOR }}.{{ VERSION_NO }}-{{ NAUTA_COMMIT }}"
  shared/centos/build:
    version: "7.6.1810"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build"
    push: False
  shared/centos/python27:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python27"
    push: False
    args:
      USER_UID: "{{ user_id }}"
  shared/centos/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python36"
    push: False
  shared/centos/build-go:
    version: "1.10.2"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/go/go1.10.2.linux-amd64.tar.gz
        dest: go1.10.2.linux-amd64.tar.gz
        checksum: 4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/godep/dep-linux-amd64
        dest: dep-linux-amd64
        checksum: 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/glide/glide-v0.13.1-linux-amd64
        dest: glide-v0.13.1-linux-amd64
        checksum: b3e126a0034ab41005b51fc9542997b632f2802ee64ad0e3850c0353ba2867cf
  shared/centos/build-go-1-12:
    version: "1.12.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go-1-12"
    push: False
    fetch_files:
      - src: https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
        dest: go1.12.1.linux-amd64.tar.gz
        checksum: 2a3fdabf665496a0db5f41ec6af7a9b15a49fbe71a85a50ca38b1f13a103aeec
  shared/centos/java:
    version: "11"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/java"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/elasticsearch/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: openjdk-11.0.2_linux-x64_bin.tar.gz
        checksum: 99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57
  shared/centos/go-apiserver-builder:
    version: "v1.9-alpha.4"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/go-apiserver-builder"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/apiserver-builder/apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        dest: apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        checksum: 6f82bb4d063b46a920f2952debd9ade19e712e7472d43e97ff09a2bf2f705ca6
  shared/build/kubernetes:
    version: "v1.11.7"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/kubernetes/v1.11.7.tar.gz
        dest: kubernetes.tar.gz
        checksum: e82b9de591dcc57403962c72290a9fd4e3690a3db488c9746abd740d3524077b
  shared/build/heapster:
    version: "v1.4.3"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/heapster"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/heapster/heapster-v1.4.3.tar.gz
        dest: heapster-v1.4.3.tar.gz
        checksum: 5a0e6fa74c8602d466338eb881af3bf4260940291e3eeb130e0ef9136c821f6c
  shared/build/tiller:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos"
      HELM_DATA_IMAGE: "shared/build/helm"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tiller"
    push: False
  shared/build/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/authbind/authbind_2.1.2.tar.gz
        dest: authbind_2.1.2.tar.gz
        checksum: 7dfb138b6ceeab34d58906be2598812d6dcc83885e650f93414d4851027c968c
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/ingress"
    push: False
  shared/build/kubernetes-dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-dashboard"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/go/go1.10.2.linux-amd64.tar.gz
        dest: go1.10.2.linux-amd64.tar.gz
        checksum: 4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/kubernetes-dashboard/kubernetes-dashboard-v1.8.3.tar.gz
        dest: kubernetes-dashboard-v1.8.3.tar.gz
        checksum: 9096f86d4107a6d23f2cff5edd1acae2faf25719a343c319860fd6a7408f761d
  shared/build/kubernetes-addons:
    version: "v1.10.11"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-addons"
    push: False
  shared/build/docker:
    version: "v18.06.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/docker"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/container-selinux-2.66-1.el7.noarch.rpm
        dest: container-selinux-2.66-1.el7.noarch.rpm
        checksum: ae35c1cd94b6c54c3678526ac6527d69c80453a8574b223bd6a6cbf9c5cc9134
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        dest: docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        checksum: 994c76793afde01ae467ead3aef7ad30369dbd9447b2752f62bb251e6f0a24ba
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/docker-ce-18.06.0.ce-3.el7.centos.src.rpm
        dest: docker-ce-18.06.0.ce-3.el7.centos.src.rpm
        checksum: 2926f66a94f5b3bcd1e3feb0d7107f2fd2713cf3f412f84dcc8fe89120c43392
  shared/build/nodejs:
    version: "v8.12.0"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nodejs"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/nodejs/node-v8.12.0.tar.gz
        dest: node-v8.12.0.tar.gz
        checksum: b4797843136edd9195c28221a1680ae52c29d867fc5fc1c99f7d6e2f2126a67b
  shared/build/nginx:
    version: "v1.15.9"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nginx"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/nginx/nginx-1.15.9-1.el7_4.ngx.src.rpm
        dest: nginx-1.15.9-1.el7_4.ngx.src.rpm
        checksum: 1db2900f2f64e338887f625292d279b401b7126edfe76a0c2bb3179980b20167
  shared/build/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/build"
    push: False
  shared/build/tensorflow/py3.6:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/build"
    push: False
  shared/build/tensorflow-serving/py2.7/1.13.0:
    version: "1.13.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.13.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/tf-serving/1.13.0.tar.gz
        dest: tensorflow-serving-v1.13.0.tar.gz
        checksum: 203da51d5de211d4fb2106c89dd4f52e119fd9ca7945b9c57675b1299bbbd381
  shared/build/tensorflow-serving/py3.6/1.13.0:
    version: "1.13.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.13.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/tf-serving/1.13.0.tar.gz
        dest: tensorflow-serving-v1.13.0.tar.gz
        checksum: 203da51d5de211d4fb2106c89dd4f52e119fd9ca7945b9c57675b1299bbbd381
  shared/run/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/run"
    push: False
  shared/run/tensorflow/py3.6:
    version: "py3"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/run"
    push: False
  shared/build/helm:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/helm"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/helm/v2.11.0.tar.gz
        dest: helm.tar.gz
        checksum: eee403cc1e05ab2eb1c6802eb7ecc4a5c544cb5971b7ee828c0b8d60fe061eb0
  shared/build/cni:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/cni"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/cni-plugins/v0.7.1.tar.gz
        dest: cni-plugins.tar.gz
        checksum: 6939d7fe0340879223cd3675b2cd1a13a41170781740cf5f856a4b06e379ffcb
  shared/build/flannel:
    version: "0.9.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/flannel"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/flannel/flannel-0.9.1.tar.gz
        dest: flannel-0.9.1.tar.gz
        checksum: 9e1ba3d52895f98b8fcc6157725735e4c446e3f3addf4971b0edb1d296f098e3
  shared/build/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/etcd"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/etcd/v3.3.9.tar.gz
        dest: etcd-v3.3.9.tar.gz
        checksum: 96639d35772108004da53e568489ce7572171d39ee507245848cc42fbd3a3032
  shared/build/consul:
    version: "v1.1.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/consul"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/consul/v1.1.0.tar.gz
        dest: consul-1.1.0.tar.gz
        checksum: 8e2539561eb07b2623d9828587e68f5ef46cee882227c7331ff26dddcdc0e9df
  shared/build/elasticsearch:
    version: "v6.6.2"
    required:
      BASE_IMAGE: "shared/nonredist/ubuntu1804"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/elasticsearch"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/elasticsearch/elasticsearch-v6.6.2.tar.gz
        dest: elasticsearch-6.6.2.tar.gz
        checksum: fde0e083022cdb90879d609de7b0e1a9813cee704bf6e32c6b72f55e54c689cc
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/elasticsearch/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: openjdk-11.0.2_linux-x64_bin.tar.gz
        checksum: 99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57
  shared/build/jq:
    version: "v1.5"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/jq"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/jq/jq-1.5.tar.gz
        dest: jq-1.5.tar.gz
        checksum: c4d2bfec6436341113419debf479d833692cc5cdab7eb0326b5a4d4fbe9f493c
  shared/build/dumb-init:
    version: "v1.2.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/dumb-init"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/dumb-init/dumb-init-1.2.1.tar.gz
        dest: dumb-init-1.2.1.tar.gz
        checksum: 56858088d9d6c911c227d196fcbfca06aff31fbe83e1519f9cabe5cf6f11b242
  shared/build/draft:
    version: "v0.13.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/draft"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/draft/draft-0.13.0.tar.gz
        dest: draft-0.13.0.tar.gz
        checksum: f9b2d7fcb5259506b60eb212af3be82f6e05f585548de2b0a1f891042e1ceb4a
  shared/build/metrics:
    version: "0.0.1"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/cli/experiment_metrics"
    push: False
  shared/utils/nginx:
    version: "v1.15.9"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
    push: False
