---

proxy:
  http_proxy: "{{ lookup('env','http_proxy') }}"
  HTTP_PROXY: "{{ lookup('env','http_proxy') }}"
  https_proxy: "{{ lookup('env','https_proxy') }}"
  HTTPS_PROXY: "{{ lookup('env','https_proxy') }}"
  no_proxy: "{{ lookup('env','no_proxy') }}"
  NO_PROXY: "{{ lookup('env','no_proxy') }}"

images: "{{ shared_images | combine(local_images | default({})) }}"

shared_images:
  shared/ubuntu:
    version: "16.04"
    method: "pull"
    push: False
    image: "ubuntu:16.04"
  shared/nonredist/ubuntu1804:
    version: "18.04"
    method: "pull"
    push: False
    image: "ubuntu:bionic-20180821"
  shared/centos:
    version: "7.6.1810"
    method: "build"
    push: False
    directory: "{{ playbook_dir }}/../../shared-containers/centos/core"
    required: {}
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/centos/centos-docker-7.6.1810.tar.xz
        dest: centos-docker.tar.xz
        checksum: 4de17ce88874786ed00aa67373e8c28c38ccbd9e87a95e91df4d931fa96a8445
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/centos/icu4c-63_1-src.tgz
        dest: icu4c-63_1-src.tgz
        checksum: 05c490b69454fce5860b7e8e2821231674af0a11d7ef2febea9a32512998cb9d
  shared/centos/rpm-packer:
    version: "7.6.1810"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/rpm-packer"
    push: False
    args:
      USER_UID: "{{ user_id }}"
  shared/docs:
    version: "v0.0.1"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../docs"
    dockerfile: "{{ playbook_dir }}/../../shared-containers/docs/Dockerfile"
    push: False
  shared/centos/build:
    version: "7.6.1810"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build"
    push: False
  shared/centos/python27:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python27"
    push: False
    args:
      USER_UID: "{{ user_id }}"
  shared/centos/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python36"
    push: False
  shared/centos/build-go:
    version: "1.12.9"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/go/go1.12.9.linux-amd64.tar.gz
        dest: go1.12.9.linux-amd64.tar.gz
        checksum: ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/godep/dep-linux-amd64
        dest: dep-linux-amd64
        checksum: 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/glide/glide-v0.13.1-linux-amd64
        dest: glide-v0.13.1-linux-amd64
        checksum: b3e126a0034ab41005b51fc9542997b632f2802ee64ad0e3850c0353ba2867cf
  shared/centos/build-go-1-12:
    version: "1.12.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go-1-12"
    push: False
    fetch_files:
      - src: https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
        dest: go1.12.1.linux-amd64.tar.gz
        checksum: 2a3fdabf665496a0db5f41ec6af7a9b15a49fbe71a85a50ca38b1f13a103aeec
  shared/centos/java:
    version: "8"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/java"
    push: False
  shared/centos/go-apiserver-builder:
    version: "v1.9-alpha.4"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/go-apiserver-builder"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/apiserver-builder/apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        dest: apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        checksum: 6f82bb4d063b46a920f2952debd9ade19e712e7472d43e97ff09a2bf2f705ca6
  shared/build/kubernetes:
    version: "v1.15.3"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/kubernetes/v1.15.3.tar.gz
        dest: kubernetes.tar.gz
        checksum: 619555fb31eefb232eaa58ba7e16143a482d7fc8c9e38dd0909caa258ac09ff3
  shared/build/heapster:
    version: "v1.4.3"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/heapster"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/heapster/heapster-v1.4.3.tar.gz
        dest: heapster-v1.4.3.tar.gz
        checksum: 5a0e6fa74c8602d466338eb881af3bf4260940291e3eeb130e0ef9136c821f6c
  shared/build/tiller:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos"
      HELM_DATA_IMAGE: "shared/build/helm"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tiller"
    push: False
  shared/build/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/authbind/authbind_2.1.2.tar.gz
        dest: authbind_2.1.2.tar.gz
        checksum: 7dfb138b6ceeab34d58906be2598812d6dcc83885e650f93414d4851027c968c
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/ingress"
    push: False
  shared/build/kubernetes-dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-dashboard"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/go/go1.12.9.linux-amd64.tar.gz
        dest: go1.12.9.linux-amd64.tar.gz
        checksum: ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/kubernetes-dashboard/kubernetes-dashboard-v1.8.3-patch-v2.tar.gz
        dest: kubernetes-dashboard-v1.8.3.tar.gz
        checksum: 2e252d8e0426ff02a1d8d9f318cbea6873dc2938410dde64429d0f2a436a30cc
  shared/build/kubernetes-addons:
    version: "v1.10.11"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-addons"
    push: False
  shared/build/docker:
    version: "v18.06.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/docker"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/container-selinux-2.66-1.el7.noarch.rpm
        dest: container-selinux-2.66-1.el7.noarch.rpm
        checksum: ae35c1cd94b6c54c3678526ac6527d69c80453a8574b223bd6a6cbf9c5cc9134
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        dest: docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        checksum: 994c76793afde01ae467ead3aef7ad30369dbd9447b2752f62bb251e6f0a24ba
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/docker/docker-ce-18.06.3.ce-3.el7.src.rpm
        dest: docker-ce-18.06.3.ce-3.el7.src.rpm
        checksum: f0a53681413dfad62c3899856bf4824be9c1922de257033f708a323d750f84e2
  shared/build/nodejs:
    version: "v8.12.0"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nodejs"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/nodejs/node-v8.12.0.tar.gz
        dest: node-v8.12.0.tar.gz
        checksum: b4797843136edd9195c28221a1680ae52c29d867fc5fc1c99f7d6e2f2126a67b
  shared/build/nginx:
    version: "v1.15.9"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nginx"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/nginx/nginx-1.15.9-1.el7_4.ngx.src.rpm
        dest: nginx-1.15.9-1.el7_4.ngx.src.rpm
        checksum: 1db2900f2f64e338887f625292d279b401b7126edfe76a0c2bb3179980b20167
  shared/build/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/build"
    push: False
  shared/build/tensorflow/py3.6:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/build"
    push: False
  shared/build/tensorflow/py2.7/1.14.0:
    version: "1.14.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.14.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/mkl/v1.14.0.tar.gz
        dest: tensorflow-v1.14.0.tar.gz
        checksum: aa2a6a1daafa3af66807cfe0bc77bfe1144a9a53df9a96bab52e3e575b3047ed
  shared/build/tensorflow/py3.6/1.14.0:
    version: "1.14.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.14.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/mkl/v1.14.0.tar.gz
        dest: tensorflow-v1.14.0.tar.gz
        checksum: aa2a6a1daafa3af66807cfe0bc77bfe1144a9a53df9a96bab52e3e575b3047ed
  shared/build/tensorflow-serving/py2.7/1.14.0:
    version: "1.14.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.14.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/tf-serving/1.14.0.tar.gz
        dest: tensorflow-serving-v1.14.0.tar.gz
        checksum: a9ec3cec537b144da632d9d204ebc2f9016734abd39774c75ad911c718d225b5
  shared/build/tensorflow-serving/py3.6/1.14.0:
    version: "1.14.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.14.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/tf-serving/1.14.0.tar.gz
        dest: tensorflow-serving-v1.14.0.tar.gz
        checksum: a9ec3cec537b144da632d9d204ebc2f9016734abd39774c75ad911c718d225b5
  shared/run/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/run"
    push: False
  shared/run/tensorflow/py3.6:
    version: "py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/run"
    push: False
  shared/build/helm:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/helm"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/helm/v2.11.0.tar.gz
        dest: helm.tar.gz
        checksum: eee403cc1e05ab2eb1c6802eb7ecc4a5c544cb5971b7ee828c0b8d60fe061eb0
  shared/build/cni:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/cni"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/cni-plugins/v0.7.1.tar.gz
        dest: cni-plugins.tar.gz
        checksum: 6939d7fe0340879223cd3675b2cd1a13a41170781740cf5f856a4b06e379ffcb
  shared/build/flannel:
    version: "0.11.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/flannel"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/flannel/flannel-0.11.0.tar.gz
        dest: flannel-0.11.0.tar.gz
        checksum: 476c886ddc06a8afcf54e181ac55579224c6be424089567a0b8d9e93dd08a053
  shared/build/etcd:
    version: "3.3.13"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/etcd"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/etcd/v3.3.13.tar.gz
        dest: etcd-v3.3.13.tar.gz
        checksum: 02df2eb25d67dafc355d19a91791f686fcf59b04cea46110c3a11fcd5e365100
  shared/build/consul:
    version: "v1.4.4"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/consul"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/consul/v1.4.4.tar.gz
        dest: consul-1.4.4.tar.gz
        checksum: 8bfb3be5c25cb20b7d8682582fa54969a4745794701efb967d37c06ab075dfe4
  shared/build/elasticsearch:
    version: "v7.3.0"
    required:
      BASE_IMAGE: "shared/nonredist/ubuntu1804"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/elasticsearch"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/elasticsearch/elasticsearch-v7.3.0.tar.gz
        dest: elasticsearch-v7.3.0.tar.gz
        checksum: 1c4299449225a2d7be59dc118b77d38f826961cf304921fa5cf3904e17262323
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/elasticsearch/openjdk-12.0.2_linux-x64_bin.tar.gz
        dest: openjdk-12.0.2_linux-x64_bin.tar.gz
        checksum: 75998a6ebf477467aa5fb68227a67733f0e77e01f737d4dfbc01e617e59106ed
  shared/build/dumb-init:
    version: "v1.2.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/dumb-init"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/dumb-init/dumb-init-1.2.1.tar.gz
        dest: dumb-init-1.2.1.tar.gz
        checksum: 56858088d9d6c911c227d196fcbfca06aff31fbe83e1519f9cabe5cf6f11b242
  shared/build/metrics:
    version: "0.0.1"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/cli/experiment_metrics"
    push: False
  shared/utils/nginx:
    version: "v1.15.9"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
    push: False
  shared/build/argo:
    version: "v2.2.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/argo"
    push: False
    args:
      ARGO_VERSION: "v2.2.1"
  shared/build/pytorch36:
    version: "v1.2.0"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/pytorch/3.6"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/pytorch/pytorch_sources_v1.2.0.tar.gz
        dest: pytorch_sources_v1.2.0.tar.gz
        checksum: 73fdbe7759e51ad4509e296b89510de34b9049f6cd8d6df93f5a178302a10d70
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/pytorch/torchvision_sources_v0.3.0.tar.gz
        dest: torchvision_sources_v0.3.0.tar.gz
        checksum: 22ceed4111ba320c8f03b787001dc71358a8555fb1e4bdd2dd06a13a719c3cbc
  shared/build/pytorch27:
    version: "v1.2.0"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/pytorch/2.7"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/pytorch/pytorch_sources_v1.2.0.tar.gz
        dest: pytorch_sources_v1.2.0.tar.gz
        checksum: 73fdbe7759e51ad4509e296b89510de34b9049f6cd8d6df93f5a178302a10d70
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/pytorch/torchvision_sources_v0.3.0.tar.gz
        dest: torchvision_sources_v0.3.0.tar.gz
        checksum: 22ceed4111ba320c8f03b787001dc71358a8555fb1e4bdd2dd06a13a719c3cbc
