---

export_images:
  - name: tiller
    value: "{{ image_local_url['dls4e/tiller'] }}"
  - name: tensorboard_service
    value: "{{ image_local_url['dls4e/tensorboard-service'] }}"
# tensorflow part
  - name: tensorflow
    value: "{{ image_local_url['dls4e/tensorflow/1.9.0py3/haswell/base'] }}"
  - name: horovod
    value: "{{ image_local_url['dls4e/horovod/py3'] }}"
  - name: horovod_py2
    value: "{{ image_local_url['dls4e/horovod/py2'] }}"
  - name: tensorflow_1.9
    value: "{{ image_local_url['dls4e/tensorflow/1.9.0py3/haswell/base'] }}"
  - name: tensorflow_1.9_py3
    value: "{{ image_local_url['dls4e/tensorflow/1.9.0py3/haswell/base'] }}"
  - name: tensorflow_1.9_py2
    value: "{{ image_local_url['dls4e/tensorflow/1.9.0py2/haswell/base'] }}"
  - name: tensorflow_1.9_py3_skylake
    value: "{{ image_local_url['dls4e/tensorflow/1.9.0py3/skylake/base'] }}"
  - name: activity-proxy
    value: "{{ image_local_url['dls4e/activity-proxy'] }}"
  - name: batch-inference
    value: "{{ image_local_url['dls4e/batch-inference'] }}"
  - name: tf-serving-sidecar
    value: "{{ image_local_url['dls4e/tf-serving-sidecar'] }}"
  - name: ps-sidecar
    value: "{{ image_local_url['dls4e/ps-sidecar'] }}"

local_images:
  dls4e/centos:
    version: "7.5.1804"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/centos"
    required:
      BASE_IMAGE: "shared/centos"
    push: True
  dls4e/kubectl:
    version: "1.10.11"
    required:
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/kubectl"
  dls4e/gui:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../applications/dls-gui"
  dls4e/elasticsearch:
    version: "v6.4.0"
    required:
      BASE_IMAGE: "shared/centos/java8"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      BUILD_IMAGE: "shared/build/elasticsearch"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/elasticsearch"
  dls4e/fluentd:
    version: "v0.12"
    required:
      BASE_IMAGE: "shared/centos"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/fluentd"
  dls4e/registry:
    version: "2.6.2"
    required:
      BUILD_IMAGE: "shared/centos/build-go"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/registry"
  dls4e/samba:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      JQ_DATA_IMAGE: "shared/build/jq"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/samba"
  dls4e/elasticsearch/curator:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/elasticsearch-curator"
  dls4e/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/etcd"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/etcd"
  dls4e/tiller:
    version: "v2.9.1"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/helm"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tiller"
  dls4e/redsocks:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build"
    method: build
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/redsocks/release-0.5.tar.gz
        dest: redsocks-0.5.tar.gz
        checksum: bbeb531d7f1986d7102f1bd6733dacce41d3f3ba7d604f1aab61c63e0ba2ee62
    directory: "{{ playbook_dir }}/../../dls4e-containers/redsocks"
  dls4e/experiment-service:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/go-apiserver-builder"
    method: build
    directory: "{{ playbook_dir }}/../../applications/experiment-service"
  dls4e/tensorflow/1.9.0py2/haswell/base:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py2.7"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py2.7/1.9.0/haswell"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py2.7/1.9.0/haswell"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow/1.9.0py3/haswell/base:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.9.0/haswell"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0/haswell"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow/1.9.0py3/skylake/base:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.9.0/skylake"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0/skylake"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.9.0/haswell"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0/haswell"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/horovod/py3:
    version: "1.9.0-py3"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/horovod/horovod-v0.15.1.tar.gz
        dest: horovod-v0.15.1.tar.gz
        checksum: 6912177f9e22a71288eb2e07cb78f8630fe2a8fab88d123b69c4ce7967593004
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.9.0/haswell"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/horovod/3.6"
  dls4e/horovod/py2:
    version: "1.9.0-py2"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/horovod/horovod-v0.15.1.tar.gz
        dest: horovod-v0.15.1.tar.gz
        checksum: 6912177f9e22a71288eb2e07cb78f8630fe2a8fab88d123b69c4ce7967593004
    required:
      BASE_IMAGE: "shared/run/tensorflow/py2.7"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py2.7/1.9.0/haswell"
      METRICS_IMAGE: "shared/build/metrics"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/horovod/2.7"
  dls4e/nginx:
    version: "1.14.0"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
  dls4e/tf/operator:
    version: "v2"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tf-operator"
  dls4e/docker:
    version: "18.03"
    required:
      BASE_IMAGE: "dls4e/kubectl"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/docker"
  dls4e/ps-sidecar:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/ps-sidecar"
  dls4e/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
      NGINX_DATA_IMAGE: "shared/build/nginx"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/ingress-nginx"
  dls4e/defaultbackend:
    version: "1.4"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/defaultbackend"
  dls4e/dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-dashboard"
    directory: "{{ playbook_dir }}/../../platform-containers/kubernetes-dashboard"
    method: build
  dls4e/tensorboard-service:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tensorboard-service"
  dls4e/activity-proxy:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/activity-proxy"
  dls4e/batch-inference:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    directory: "{{ playbook_dir }}/../../applications/batch-inference"
  dls4e/tf-serving-sidecar:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tf-serving-sidecar"
  dls4e/docs:
    version: "v0.0.1"
    required:
      BASE_IMAGE: "shared/utils/nginx"
      DOCS_IMAGE: "shared/centos/docs"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/docs-nginx"

subcharts:
  dls4e-registry:
    registry:
      version: 2.6.2
      path: "{{ playbook_dir }}/../../dls4e-registry-charts/registry"
  dls4e:
    gui:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/gui"
      chart_values:
        image: "{{ image_local_url['dls4e/gui'] }}"
    admin-account:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/admin-account"
    experiments:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/experiments"
    configuration:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/configuration"
    commons:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/commons"
      chart_values:
        docker_image: "{{ image_local_url['dls4e/docker'] }}"
    docker-registry:
      version: 1.1.1
      path: "{{ playbook_dir }}/../../dls4e-charts/docker-registry"
      chart_values:
        image: "{{ image_local_url['dls4e/registry'] }}"
        gc_image: "{{ image_local_url['dls4e/kubectl'] }}"
    elasticsearch:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/elasticsearch"
      chart_values:
        image: "{{ image_local_url['dls4e/elasticsearch'] }}"
        init_image: "{{ image_local_url['dls4e/centos'] }}"
    elasticsearch-curator:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/elasticsearch-curator"
      chart_values:
        image: "{{ image_local_url['dls4e/elasticsearch/curator'] }}"
        init_image: "{{ image_local_url['dls4e/centos'] }}"
    fluentd:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/fluentd"
      chart_values:
        image: "{{ image_local_url['dls4e/fluentd'] }}"
        centos_image: "{{ image_local_url['dls4e/centos'] }}"
    samba:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/samba"
      chart_values:
        image: "{{ image_local_url['dls4e/samba'] }}"
    redsocks:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/redsocks"
      conditions: features.redsocks
      feature_enabled: False
      chart_values:
        image: "{{ image_local_url['dls4e/redsocks'] }}"
        Interfaces: cni0
    registry-nginx:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/registry-nginx"
      chart_values:
        image: "{{ image_local_url['dls4e/nginx'] }}"
    experiment-service:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/experiment-service"
      chart_values:
        service_image: "{{ image_local_url['dls4e/experiment-service'] }}"
        etcd_image: "{{ image_local_url['dls4e/etcd'] }}"
        etcd_gc_image: "{{ image_local_url['dls4e/kubectl'] }}"
    tf:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/tf"
      chart_values:
        image: "{{ image_local_url['dls4e/tf/operator'] }}"
        tfimage: "{{ image_local_url['dls4e/tensorflow/1.9.0py3/haswell/base'] }}"
    ingress:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/ingress"
      chart_values:
        image: "{{ image_local_url['dls4e/ingress'] }}"
        defaultbackend_image: "{{ image_local_url['dls4e/defaultbackend'] }}"
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dashboard"
      chart_values:
        image: "{{ image_local_url['dls4e/dashboard'] }}"
    documentation-service:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/documentation-service"
      chart_values:
        image: "{{ image_local_url['dls4e/docs'] }}"
    kube-batch-queue:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/kube-batch-queue"
