---

export_images:
  - name: tiller
    value: "{{ image_local_url['nauta/tiller'] }}"
  - name: tensorboard_service
    value: "{{ image_local_url['nauta/tensorboard-service'] }}"
# tensorflow part
  - name: tensorflow
    value: "{{ image_local_url['nauta/tensorflow/1.14.0py3/base'] }}"
  - name: horovod
    value: "{{ image_local_url['nauta/horovod/py3'] }}"
  - name: horovod_py2
    value: "{{ image_local_url['nauta/horovod/py2'] }}"
  - name: tensorflow_1.14
    value: "{{ image_local_url['nauta/tensorflow/1.14.0py3/base'] }}"
  - name: tensorflow_1.14_py3
    value: "{{ image_local_url['nauta/tensorflow/1.14.0py3/base'] }}"
  - name: tensorflow_1.14_py2
    value: "{{ image_local_url['nauta/tensorflow/1.14.0py2/base'] }}"
  - name: activity-proxy
    value: "{{ image_local_url['nauta/activity-proxy'] }}"
  - name: batch-inference
    value: "{{ image_local_url['nauta/batch-inference'] }}"
  - name: tf-serving-sidecar
    value: "{{ image_local_url['nauta/tf-serving-sidecar'] }}"
  - name: tfjob-multinode-sidecar
    value: "{{ image_local_url['nauta/tfjob-multinode-sidecar'] }}"
  - name: pytorch
    value: "{{ image_local_url['nauta/pytorch/py3'] }}"
  - name: pytorch_py2
    value: "{{ image_local_url['nauta/pytorch/py2'] }}"
  - name: openvino-ms
    value: "{{ image_local_url['nauta/openvino-ms'] }}"
  - name: openvino-mo
    value: "{{ image_local_url['nauta/openvino-mo'] }}"

local_images:
  nauta/centos:
    version: "7.6.1810"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/centos"
    required:
      BASE_IMAGE: "shared/centos"
    push: True
  nauta/kubectl:
    version: "1.10.11"
    required:
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/kubectl"
  nauta/gui:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../applications/nauta-gui"
  nauta/elasticsearch:
    version: "v6.6.2"
    required:
      BASE_IMAGE: "shared/centos/java"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      BUILD_IMAGE: "shared/build/elasticsearch"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/elasticsearch"
  nauta/elasticsearch/proxy:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/elasticsearch-proxy"
  nauta/fluentd:
    version: "v0.12"
    required:
      BASE_IMAGE: "shared/centos"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/fluentd"
  nauta/registry:
    required:
      BUILD_IMAGE: "shared/centos/build-go"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/registry"
    version: "2.7.1"
  nauta/docker:
    version: "18.06"
    required:
      BASE_IMAGE: "nauta/kubectl"
      DOCKER_RPM_IMAGE: "shared/build/docker"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/docker"
  nauta/samba:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/samba"
  nauta/elasticsearch/curator:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/elasticsearch-curator"
  nauta/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/etcd"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/etcd"
  nauta/tiller:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/helm"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/tiller"
  nauta/redsocks:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build"
    method: build
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/redsocks/release-0.5.tar.gz
        dest: redsocks-0.5.tar.gz
        checksum: bbeb531d7f1986d7102f1bd6733dacce41d3f3ba7d604f1aab61c63e0ba2ee62
    directory: "{{ playbook_dir }}/../../nauta-containers/redsocks"
  nauta/experiment-service:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/go-apiserver-builder"
    method: build
    directory: "{{ playbook_dir }}/../../applications/experiment-service"
  nauta/tensorflow/1.14.0py2/base:
    version: "1.14.0-py2"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py2.7"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py2.7/1.14.0"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py2.7/1.14.0"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    squash: True
    directory: "{{ playbook_dir }}/../../nauta-containers/tensorflow"
  nauta/tensorflow/1.14.0py3/base:
    version: "1.14.0-py3"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.14.0"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py3.6/1.14.0"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    squash: True
    directory: "{{ playbook_dir }}/../../nauta-containers/tensorflow"
  nauta/tensorflow:
    version: "1.14.0-py3"
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.14.0"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py3.6/1.14.0"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    squash: True
    directory: "{{ playbook_dir }}/../../nauta-containers/tensorflow"
  nauta/horovod/py3:
    version: "0.16.4-py3"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/horovod/v0.16.4.tar.gz
        dest: horovod-v0.16.4.tar.gz
        checksum: 1f7b7a3926c4b169ecbd20a4eb97d15d6720c7593689476e3fd67371937122b5
    required:
      BASE_IMAGE: "shared/run/tensorflow/py3.6"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.14.0"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      METRICS_IMAGE: "shared/build/metrics"
    method: build
    squash: True
    directory: "{{ playbook_dir }}/../../nauta-containers/horovod/3.6"
  nauta/horovod/py2:
    version: "0.16.4-py2"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/horovod/v0.16.4.tar.gz
        dest: horovod-v0.16.4.tar.gz
        checksum: 1f7b7a3926c4b169ecbd20a4eb97d15d6720c7593689476e3fd67371937122b5
    required:
      BASE_IMAGE: "shared/run/tensorflow/py2.7"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py2.7/1.14.0"
      METRICS_IMAGE: "shared/build/metrics"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    squash: True
    directory: "{{ playbook_dir }}/../../nauta-containers/horovod/2.7"
  nauta/nginx:
    version: "1.14.0"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
  nauta/docs:
    version: "v0.0.1"
    required:
      BASE_IMAGE: "shared/docs"
      NGINX_IMAGE: "shared/utils/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../applications/nauta-docs"
    dockerfile: "{{ playbook_dir }}/../../applications/nauta-docs/Dockerfile"
    args:
      DOCS_VERSION: "{{ VERSION_MAJOR }}.{{ VERSION_MINOR }}.{{ VERSION_NO }}-{{ NAUTA_COMMIT }}"
  nauta/tf/operator:
    version: "v2"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/tf-operator"
  nauta/tfjob-multinode-sidecar:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tfjob-multinode-sidecar"
  nauta/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
      NGINX_DATA_IMAGE: "shared/build/nginx"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/ingress-nginx"
  nauta/defaultbackend:
    version: "1.4"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/defaultbackend"
  nauta/dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-dashboard"
    directory: "{{ playbook_dir }}/../../platform-containers/kubernetes-dashboard"
    method: build
  nauta/tensorboard-service:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tensorboard-service"
  nauta/activity-proxy:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/activity-proxy"
  nauta/batch-inference:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      METRICS_IMAGE: "shared/build/metrics"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.14.0"
      TENSORFLOW_SERVING_BUILD_IMAGE: "shared/build/tensorflow-serving/py2.7/1.14.0"
    method: build
    directory: "{{ playbook_dir }}/../../applications/batch-inference"
  nauta/tf-serving-sidecar:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tf-serving-sidecar"
  nauta/kube-batch:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/kube-batch"
  nauta/gitea:
    version: "1.6.1"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/gitea/v1.6.1.tar.gz
        dest: gitea-v1.6.1.tar.gz
        checksum: cf4e283df164841f1b302e26ae1cbcdea68539de41f2086533c095b264df9a7c
    required:
      BASE_IMAGE: "shared/centos/build-go-1-12"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/gitea"
  nauta/postgres:
    version: "9.2.24"
    required:
      BASE_IMAGE: "shared/centos"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/postgres"
  nauta/memcached:
    version: "1.5.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/memcached"
  nauta/buildkit:
    version: "master"
    required:
      BASE_IMAGE: "shared/centos/build-go-1-12"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/buildkit/buildkit-2019-04-08--cbfb5c476a09189272279495897993f5387781e1---v0.4.0-120-gcbfb5c47.tgz
        dest: buildkit-2019-04-08--cbfb5c476a09189272279495897993f5387781e1---v0.4.0-120-gcbfb5c47.tgz
        checksum: 7d37ac5769781acfa73bdf4ec1906ff2817c474b97a9c5e0cd86c07973741647
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/buildkit/runc-2019-04-08--6635b4f0c6af3810594d2770f662f34ddc15b40d.tgz
        dest: runc-2019-04-08--6635b4f0c6af3810594d2770f662f34ddc15b40d.tgz
        checksum: dc0a26cb7a14837c86abfdde71e9d29e12008298660d77d4de1de162726c8ddd
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/buildkit"
  nauta/argo-controller:
    version: "v2.2.1"
    required:
      ARGO_IMAGE: "shared/build/argo"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/argo/argo-controller"
  nauta/argoexec:
    version: "v2.2.1"
    required:
      ARGO_IMAGE: "shared/build/argo"
      BASE_IMAGE: "shared/centos"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      DOCKER_RPM_IMAGE: "shared/build/docker"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/argo/argoexec"
  nauta/pytorch/py3:
    version: "1.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      PYTORCH_IMAGE: "shared/build/pytorch36"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/pytorch-base/3.6"
  nauta/pytorch/py2:
    version: "1.0"
    required:
      BASE_IMAGE: "shared/centos/python27"
      PYTORCH_IMAGE: "shared/build/pytorch27"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/pytorch-base/2.7"
  nauta/pytorch-operator:
    version: "v0.4.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/pytorch-operator"
  nauta/openvino-ms:
    version: "2019.07.24"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/openvino-model-server"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/NAUTA/downloads/openvino/openvino-model-server-00494373591e6b5a37664dc0e82abb491f8c9207.tar.gz
        dest: openvino-model-server.tar.gz
        checksum: cfc8260bf881ebb47579916feeb754201f8c97baf4158b031430c415c1790143
  nauta/openvino-mo:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/py3.6/1.14.0"
    method: build
    directory: "{{ playbook_dir }}/../../nauta-containers/openvino-mo"

# WARNING
# setting chart_values will work only if chart does not contain values.yaml file
subcharts:
  nauta-registry:
    registry:
      version: 2.7.1
      path: "{{ playbook_dir }}/../../nauta-registry-charts/registry"
  nauta:
    gui:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../nauta-charts/gui"
      chart_values:
        image: "{{ image_local_url['nauta/gui'] }}"
    admin-account:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/admin-account"
    experiments:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/experiments"
    configuration:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/configuration"
    commons:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/commons"
      chart_values:
        docker_image: "{{ image_local_url['nauta/docker'] }}"
    docker-registry:
      version: 1.1.1
      path: "{{ playbook_dir }}/../../nauta-charts/docker-registry"
      chart_values:
        image: "{{ image_local_url['nauta/registry'] }}"
        gc_image: "{{ image_local_url['nauta/kubectl'] }}"
    kube-batch:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/kube-batch"
      chart_values:
        image: "{{ image_local_url['nauta/kube-batch'] }}"
    elasticsearch:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../nauta-charts/elasticsearch"
      chart_values:
        image: "{{ image_local_url['nauta/elasticsearch'] }}"
        init_image: "{{ image_local_url['nauta/centos'] }}"
        proxy_image: "{{ image_local_url['nauta/elasticsearch/proxy'] }}"
    elasticsearch-curator:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../nauta-charts/elasticsearch-curator"
      chart_values:
        image: "{{ image_local_url['nauta/elasticsearch/curator'] }}"
        init_image: "{{ image_local_url['nauta/centos'] }}"
    fluentd:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../nauta-charts/fluentd"
      chart_values:
        image: "{{ image_local_url['nauta/fluentd'] }}"
        centos_image: "{{ image_local_url['nauta/centos'] }}"
    samba:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/samba"
      chart_values:
        image: "{{ image_local_url['nauta/samba'] }}"
    redsocks:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/redsocks"
      conditions: features.redsocks
      feature_enabled: False
      chart_values:
        image: "{{ image_local_url['nauta/redsocks'] }}"
        Interfaces: cni0
    registry-nginx:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/registry-nginx"
      chart_values:
        image: "{{ image_local_url['nauta/nginx'] }}"
    experiment-service:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/experiment-service"
      chart_values:
        service_image: "{{ image_local_url['nauta/experiment-service'] }}"
        etcd_image: "{{ image_local_url['nauta/etcd'] }}"
        etcd_gc_image: "{{ image_local_url['nauta/kubectl'] }}"
    tf:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../nauta-charts/tf"
      chart_values:
        image: "{{ image_local_url['nauta/tf/operator'] }}"
        tfimage: "{{ image_local_url['nauta/tensorflow/1.14.0py3/base'] }}"
    ingress:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/ingress"
      chart_values:
        image: "{{ image_local_url['nauta/ingress'] }}"
        defaultbackend_image: "{{ image_local_url['nauta/defaultbackend'] }}"
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../nauta-charts/dashboard"
      chart_values:
        image: "{{ image_local_url['nauta/dashboard'] }}"
    documentation-service:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../nauta-charts/documentation-service"
      chart_values:
        image: "{{ image_local_url['nauta/docs'] }}"
    argo-controller:
      version: 2.2.1
      path: "{{ playbook_dir }}/../../nauta-charts/argo-controller"
      chart_values:
        image: "{{ image_local_url['nauta/argo-controller'] }}"
        image2: "{{ image_local_url['nauta/argoexec'] }}"
    gitea:
      version: 1.6.1
      path: "{{ playbook_dir }}/../../nauta-charts/gitea"
      chart_values:
        image: "{{ image_local_url['nauta/gitea'] }}"
    buildkit:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../nauta-charts/buildkit"
      chart_values:
        image: "{{ image_local_url['nauta/buildkit'] }}"
    pytorch-operator:
      version: 0.4.0
      path: "{{ playbook_dir }}/../../nauta-charts/pytorch-operator"
      chart_values:
        image: "{{ image_local_url['nauta/pytorch-operator'] }}"
