---

- name: Run local tasks
  hosts: localhost
  become: False
  handlers:
  - name: Remove finalizer container
    docker_container:
      name: "finalizer-{{ build_name }}-{{ user }}-{{ version }}"
      state: absent
      stop_timeout: 0
      timeout: 120
      force_kill: True
  - name: Remove build dir
    file:
      path: "{{ build_dir }}"
      state: absent
  roles:
    - role: finalize
