# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TensorBoardPort: 8888
TensorIPythonPort: 6006

commandline:
  args:
    {% for arg in DLS4e.CommandLine %}
    - {{ arg }}
    {% endfor %}

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ DLS4e.ExperimentImage }}

service:
  type: ClusterIP

worker_resources:
  requests:
    cpu: 76
    memory: 240Gi
  limits:
    cpu: 76
    memory: 240Gi

worker_cpu: null
worker_memory: null

ps_resources:
  requests:
    cpu: 76
    memory: 240Gi
  limits:
    cpu: 76
    memory: 240Gi

ps_cpu: null
ps_memory: null

sidecar_resources:
  requests:
    cpu: 0.01
    memory: 1Gi

sidecar_cpu: null
sidecar_memory: null

experimentName: {{ DLS4e.ExperimentName }} 
registryPort: {{ DLS4e.RegistryPort }}
workersCount: 3
psSidecarLoggingLevel: "WARNING"
pServersCount: 1
